#!/bin/bash
export OC_DISABLE_DOT_ACCESS_WARNING=1

mmf_run config="projects/visual_bert/configs/hateful_memes/from_coco.yaml" \
        model="visual_bert" \
        dataset=hateful_memes \
        run_type=train_val \
        checkpoint.max_to_keep=1 \
        checkpoint.resume_zoo=visual_bert.pretrained.cc.full \
        training.tensorboard=True \
        training.checkpoint_interval=50 \
        training.evaluation_interval=50 \
        training.max_updates=1000 \
        training.log_interval=100 \
        dataset_config.hateful_memes.max_features=100 \
        dataset_config.hateful_memes.annotations.train[0]=$9 \
        dataset_config.hateful_memes.annotations.val[0]=hateful_memes/defaults/annotations/dev_unseen.jsonl \
        dataset_config.hateful_memes.annotations.test[0]=hateful_memes/defaults/annotations/test_unseen.jsonl \
        dataset_config.hateful_memes.features.train[0]=$8 \
        dataset_config.hateful_memes.features.val[0]=$8 \
        dataset_config.hateful_memes.features.test[0]=$8 \
        training.lr_ratio=$2 \
        training.use_warmup=True \
        training.warmup_factor=$5 \
        training.warmup_iterations=$6 \
        optimizer.params.lr=5.0e-05 \
      	training.batch_size=$7 \
      	scheduler.params.num_warmup_steps=$3 \
      	scheduler.type=$4 \
      	scheduler.params.num_training_steps=1000 \
        env.tensorboard_logdir=logs/fit/$1 \
        env.save_dir=./$1 \
